### ISSUE TITLE
java error

### ISSUE THREAD

**Issue by crowland88** [WarlaxZ/alexa-home-controller#1]
please help I can Run the server (node server.js) I get a java error.
I have also tried cmd still no luck
script:
C:\users\chris\downloads\alexa-home-controller-master\alexa-home-controller-master\server.js
line: 2
char:1
error Object expected
code: 800A138F
source: Microsoft JScript runtime error

**Comment by WarlaxZ** [comment]
Hi,

So it isn't actually a java program, and you will need node installed to run this.

Once you have installed node, then type the following commands

npm install -g grunt
grunt
node server.js
